### ISSUE TITLE
Push Notifications via PWA

### ISSUE THREAD

**Issue by BubbaJoe** [Tomburgs/pwa-boilerplate#40]
Hey, you mentioned that push notification was possible in the website description. Can you explain how to do this on an iOS?

**Comment by Tomburgs** [comment]
Hey, @BubbaJoe.

We currently don't support push notifications because of this exact reason, that iOS currently does not have that functionality available for PWAs. There's some news saying that Apple is working on it, but I would advise taking it with a grain of salt.

If you have to have push notifications on iOS in your PWA, then currently the only solution is to put your application on the App Store and ask for push notification permissions, however there's a few drawbacks to this:
- There's some hoops you have to jump through to have it accepted on the App Store.
- Your users will have to download your app from the App Store.
- You have to register for the "Apple Developer Program", annual membership costs 99$.

If you have any other questions, please let me know.

**Comment by KurtMar** [comment]
Please note that iOS will have Web Push in the next minor release 16.4, expected to be released during March or April 2023: https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/

"Now with iOS and iPadOS 16.4 beta 1, we are adding support for Web Push to Home Screen web apps. Web Push makes it possible for web developers to send push notifications to their users through the use of [Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API), [Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API), and [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) all working together."

**Comment by Tomburgs** [comment]
That seems sweet, @KurtMar. Thanks for letting me know :')
